version: '3'

services:
  postgres:
    image: 'postgres:10.21'
    container_name: 'java_postgres'
    environment:
    - 'POSTGRES_USER=admin'
    - 'POSTGRES_PASSWORD=admin'
    - 'POSTGRES_DB=pet'

    ports:
    - 5432:5432

  app:
    build: ./
    container_name: 'java-pet-app'
    ports:
    - 8080:8080