spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    url: jdbc:postgresql://localhost:5432/pet
#    url: jdbc:postgresql://postgres:5432/pet
    password: admin
  data:
    rest:
      default-page-size: 10
      max-page-size: 40
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#    spring:
#      jpa:
#        properties:
#          jakarta:
#            persistence:
#              schema-generation:
#                scripts:
#                  create-target: create.sql
#                  action: create
#                  create-source: metadata
